name: build script for clean.c 
on: 
  push:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: build cleantest 
        run: make cleantest; ./cleantest <wbcd.txt >cleaned_wbcd.txt